#!/usr/bin/env python3
"""Insert test deals with AI enhancement fields populated."""

import sqlite3
from datetime import datetime, timedelta, timezone
import json

DB_PATH = "/home/deploy/dealscout/dealscout.db"

test_deals = [
    {
        "title": "NVIDIA GeForce RTX 4070 Ti Gaming GPU",
        "source": "Swoopa",
        "asking_price": 450.00,
        "listing_url": "https://swoopa.com/item/12345",
        "status": "flagged",
        "category": "Graphics Cards",
        "brand": "NVIDIA",
        "model": "RTX 4070 Ti",
        "condition": "used",
        "market_value": 650.00,
        "estimated_profit": 140.00,
        "deal_score": 85,
        "risk_level": "low",
        "effort_level": "low",
        "demand_indicator": "high",
        "flip_speed_prediction": "fast",
        "price_trend": "stable",
        "price_trend_note": "Prices stable, high demand for gaming GPUs",
        "has_product_photos": True,
        "photo_quality": "good",
        "seller_username": "tech_seller_99",
        "seller_rating": "98.5%",
        "repair_needed": False,
    },
    {
        "title": "iPhone 14 Pro Max 256GB - Cracked Screen AS-IS",
        "source": "Swoopa",
        "asking_price": 380.00,
        "listing_url": "https://swoopa.com/item/12346",
        "status": "needs_condition",
        "category": "Smartphones",
        "brand": "Apple",
        "model": "iPhone 14 Pro Max",
        "condition": "needs_repair",
        "market_value": 750.00,
        "estimated_profit": 220.00,
        "deal_score": 72,
        "risk_level": "medium",
        "effort_level": "medium",
        "demand_indicator": "high",
        "flip_speed_prediction": "medium",
        "repair_needed": True,
        "repair_keywords": json.dumps(["cracked screen", "as-is"]),
        "repair_feasibility": "moderate",
        "repair_notes": "Screen replacement required. Common repair with readily available parts.",
        "repair_part_needed": "iPhone 14 Pro Max OLED Screen Assembly",
        "repair_part_cost": 89.99,
        "repair_part_url": "https://ebay.com/itm/iphone-14-pro-max-screen",
        "repair_labor_estimate": 40.00,
        "repair_total_estimate": 129.99,
        "true_profit": 90.01,
        "has_product_photos": True,
        "photo_quality": "fair",
        "seller_username": "phone_parts_guy",
        "seller_rating": "95.2%",
        "price_trend": "down",
        "price_trend_note": "iPhone 15 release pushing down 14 Pro prices",
    },
    {
        "title": "PS5 Bundle - Console + 2 Controllers + 5 Games",
        "source": "Swoopa",
        "asking_price": 420.00,
        "listing_url": "https://swoopa.com/item/12347",
        "status": "flagged",
        "category": "Gaming Consoles",
        "brand": "Sony",
        "model": "PlayStation 5",
        "condition": "used",
        "market_value": 580.00,
        "estimated_profit": 95.00,
        "deal_score": 78,
        "risk_level": "low",
        "effort_level": "medium",
        "demand_indicator": "high",
        "flip_speed_prediction": "fast",
        "is_bundle": True,
        "bundle_items": json.dumps(["PS5 Console", "DualSense Controller x2", "Spider-Man 2", "God of War Ragnarok", "Horizon Forbidden West", "Gran Turismo 7", "Ratchet & Clank"]),
        "bundle_value_per_item": 72.50,
        "accessory_completeness": "All cables included, original box",
        "has_product_photos": True,
        "photo_quality": "good",
        "seller_username": "gaming_deals",
        "seller_rating": "99.1%",
        "repair_needed": False,
        "price_trend": "stable",
        "price_trend_note": "PS5 prices stable, bundles sell quickly",
    },
    {
        "title": "MacBook Pro 14\" M3 Pro - Battery Issues FOR PARTS",
        "source": "Swoopa",
        "asking_price": 850.00,
        "listing_url": "https://swoopa.com/item/12348",
        "status": "needs_condition",
        "category": "Laptops",
        "brand": "Apple",
        "model": "MacBook Pro 14 M3 Pro",
        "condition": "needs_repair",
        "market_value": 1800.00,
        "estimated_profit": 700.00,
        "deal_score": 65,
        "risk_level": "high",
        "effort_level": "high",
        "demand_indicator": "high",
        "flip_speed_prediction": "medium",
        "repair_needed": True,
        "repair_keywords": json.dumps(["battery issues", "for parts"]),
        "repair_feasibility": "difficult",
        "repair_notes": "Battery replacement on M3 MacBooks requires specialized tools. Consider Apple authorized repair.",
        "repair_part_needed": "MacBook Pro 14 M3 Battery",
        "repair_part_cost": 180.00,
        "repair_part_url": "https://ebay.com/itm/macbook-pro-14-battery",
        "repair_labor_estimate": 120.00,
        "repair_total_estimate": 300.00,
        "true_profit": 400.00,
        "has_product_photos": True,
        "photo_quality": "fair",
        "seller_username": "mac_parts_outlet",
        "seller_rating": "92.8%",
        "price_trend": "up",
        "price_trend_note": "M3 MacBooks holding value well",
    },
    {
        "title": "DJI Mini 4 Pro Fly More Combo - SEALED",
        "source": "Swoopa",
        "asking_price": 680.00,
        "listing_url": "https://swoopa.com/item/12349",
        "status": "flagged",
        "category": "Drones",
        "brand": "DJI",
        "model": "Mini 4 Pro",
        "condition": "new",
        "market_value": 960.00,
        "estimated_profit": 185.00,
        "deal_score": 92,
        "risk_level": "low",
        "effort_level": "low",
        "demand_indicator": "high",
        "flip_speed_prediction": "fast",
        "accessory_completeness": "Factory sealed, Fly More Combo with extra batteries",
        "has_product_photos": True,
        "photo_quality": "good",
        "seller_username": "drone_warehouse",
        "seller_rating": "99.5%",
        "repair_needed": False,
        "price_trend": "stable",
        "price_trend_note": "Strong demand for Mini 4 Pro, prices stable",
        "part_numbers": json.dumps(["CP.MA.00000731.01"]),
    },
    {
        "title": "Samsung Galaxy S24 Ultra - No Power WON'T TURN ON",
        "source": "Swoopa",
        "asking_price": 280.00,
        "listing_url": "https://swoopa.com/item/12350",
        "status": "needs_condition",
        "category": "Smartphones",
        "brand": "Samsung",
        "model": "Galaxy S24 Ultra",
        "condition": "needs_repair",
        "market_value": 900.00,
        "estimated_profit": 450.00,
        "deal_score": 55,
        "risk_level": "high",
        "effort_level": "high",
        "demand_indicator": "medium",
        "flip_speed_prediction": "slow",
        "repair_needed": True,
        "repair_keywords": json.dumps(["no power", "won't turn on"]),
        "repair_feasibility": "professional",
        "repair_notes": "Could be battery, charging port, or motherboard. High risk without diagnosis.",
        "repair_part_needed": "Samsung S24 Ultra Battery + Charging Port",
        "repair_part_cost": 65.00,
        "repair_part_url": "https://ebay.com/itm/s24-ultra-battery",
        "repair_labor_estimate": 80.00,
        "repair_total_estimate": 145.00,
        "true_profit": 305.00,
        "has_product_photos": True,
        "photo_quality": "poor",
        "seller_username": "parts_salvage",
        "seller_rating": "88.3%",
        "price_trend": "down",
        "price_trend_note": "Newer models driving prices down",
    },
]

def insert_deals():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    now = datetime.now(timezone.utc).isoformat()

    for deal in test_deals:
        deal["created_at"] = now

        columns = list(deal.keys())
        values = list(deal.values())
        placeholders = ", ".join(["?" for _ in values])
        col_names = ", ".join(columns)

        cursor.execute(f"INSERT INTO deals ({col_names}) VALUES ({placeholders})", values)
        print(f"Inserted: {deal['title'][:50]}...")

    conn.commit()
    conn.close()
    print(f"\nSuccessfully inserted {len(test_deals)} test deals!")

if __name__ == "__main__":
    insert_deals()
